with-expecter: true
packages:
  github.com/green-ecolution/green-ecolution-backend/internal/service:
    config: 
      dir: ./internal/service/_mock
    interfaces:
      InfoService:
      MqttService:
      TreeService:
      TreeClusterService:
      GeoClusterLocator:
      AuthService:
      RegionService:
      SensorService:
      VehicleService:
      PluginService:
      WateringPlanService:
      Service:
      ServicesInterface:
  github.com/green-ecolution/green-ecolution-backend/internal/storage:
    config: 
      dir: ./internal/storage/_mock
    interfaces:
      InfoRepository:
      SensorRepository:
      TreeRepository:
      TreeClusterRepository:
      AuthRepository:
      UserRepository:
      RegionRepository:
      ImageRepository:
      VehicleRepository:
      WateringPlanRepository:
      RoutingRepository:
      S3Repository:
  github.com/green-ecolution/green-ecolution-backend/internal/storage/postgres/_sqlc:
    config: 
      dir: ./internal/storage/_mock
      outpkg: storage
    interfaces:
      Querier:
