dashboard:
    title: ENC[AES256_GCM,data:7wVdmvzFuNQiZOpn52hpNJeOkVZ1u4oLhtmdWQ+gPg==,iv:63To6n7LvlIFRKSJhVHOMHG5r1gldmkRv00gMwxQuAk=,tag:NOJSBMOTzEKXy34pkBQK9Q==,type:str]
server:
    port: ENC[AES256_GCM,data:pdATDw==,iv:OVnw9nseBuvvvzaKcoTsF4oH/H8B5ce/3EoufED3ueA=,tag:kfBclZ9p/DFPV2F4zvK1xw==,type:int]
    development: ENC[AES256_GCM,data:Wj9CPQ==,iv:mJE7sBh0lCqBe6qUwOBEkgycAi7TeZLl2TyAcHVieRU=,tag:xGWWzuJ7JI1LEqWY1jyjtQ==,type:bool]
    app_url: ENC[AES256_GCM,data:Fe2eBTbuttSMPPoKkNI/fS7a2rzy,iv:Hlp/wwuUTJpk+eQpyZgBTR3roZpJ8ZQjE9G+M9EHP7o=,tag:x/BciRWZ/F0AfMC8ioNDkg==,type:str]
    logs:
        level: ENC[AES256_GCM,data:EuCOssM=,iv:4DxcZIzjXzcGWdQiXgConjY5VDHJKHOBFgg+eY0ybCA=,tag:5iUK8mKHTfqAVOJI5VKA6Q==,type:str]
        format: ENC[AES256_GCM,data:x+5JvHhxxw==,iv:MwpX+gleRju9p2a0AzjV3FF4hMehBiNvTpVF/6tB15c=,tag:nacyetijjmCp97XNYIJ8GQ==,type:str]
    database:
        host: ENC[AES256_GCM,data:os8wo9W7GE79,iv:mDX3UBDNpGWCTfKZAiNDiPCMcsBEg7RP2bbNFSgO4kQ=,tag:hvh3zkVujrdaInwblgio8A==,type:str]
        port: ENC[AES256_GCM,data:if+u2A==,iv:mBw3J5Vy3LXjSrmn0f7O5EV+ysugypJ485bkq5BHnlM=,tag:/beReH1ItctH0ntUOYqdvQ==,type:int]
        username: ENC[AES256_GCM,data:FgoTNn3pdHc=,iv:r/dfi5xQPQIQHZ/878R/1qp0NznyjwgRmhppnPs2TH4=,tag:CtCFXnVtxcvtzrNXUp0Iyg==,type:str]
        password: ENC[AES256_GCM,data:4biJYdOUJqw=,iv:3o6uSR444IBJNZs5LoN9PJg6RvKXgezmcplVjCAaPQo=,tag:VT13tbthAf/pJ/lWYnTkHg==,type:str]
        name: ENC[AES256_GCM,data:Xkp2laRSgEc=,iv:QWWJ+LZSIbtmE+YKcdiH6acNBB8DfIz9ap6zSk7ikj4=,tag:mY5z8sV+Yj+NZPEuXNVTQw==,type:str]
routing:
    start_point:
        - ENC[AES256_GCM,data:hmGdhpCfc4fi5hDDu3Va6OQ=,iv:Wl5JFmkUpVUUANRSbOTY5a8It0oqwJ8AF8IcbXtuLmU=,tag:pPEDkbOpP6TU22d6xlf91g==,type:float]
        - ENC[AES256_GCM,data:Rq/mlZ4F0UZMdTqRmiqcV7GV,iv:sSjsalbRVTLwehEHOhU4uqTUr1jEZqIe4zsvl9CwOhI=,tag:YutMOh+H8o48jKEVoHpFYg==,type:float]
    end_point:
        - ENC[AES256_GCM,data:FBRExeK7JLRYGavYI9W2FkQ=,iv:GZa9pCNVKTXGoXQ1hr6OJoYSGuxWXubJIsmyGRHqFOI=,tag:eEwSOZjPy/xT9hF+FeiF+w==,type:float]
        - ENC[AES256_GCM,data:Knz3cR+m/f3xHoEQ7geLQk99,iv:C7Y6hu/xalx2sgkS3di5CkzY7KurDcjraOyU5XBE/FM=,tag:TK5hr74aOytEjAFgYn6g/g==,type:float]
    watering_point:
        - ENC[AES256_GCM,data:KAp4O5m4u06ZuDeYaj5cxD0=,iv:1qqb5zyyGIrDDlCGxGM40DBCy6SqZ083n8olqgUE47Q=,tag:5wmQaK42Zojbs8KqVwi5Yw==,type:float]
        - ENC[AES256_GCM,data:dKcD2oDeGwZ8zVuiG2eMO52e,iv:1uXUguhF0981xG8SibF0wzMFsosHwkv054P3Iz3KIGU=,tag:ee0skRBxlGJWINzpJsD83w==,type:float]
    valhalla:
        host: ENC[AES256_GCM,data:W9RNaH9COWLGwbbuCTdDQMCQLXfR,iv:j9dteekLRl00NyLqEWgm6e787WzXZvnMwF7ihBS9RDI=,tag:Yai8uagL9KYQLPyKgMzCmA==,type:str]
        optimization:
            vroom:
                host: ENC[AES256_GCM,data:2cq52mambTkeLwUb+qfoL+96Z5Zr,iv:BbQNPOTB1w+g/5aC5Wank294qmRJxk1mFLzzV9avmyQ=,tag:umAihg2u+cxEi/UmE5XAKw==,type:str]
    ors:
        host: ENC[AES256_GCM,data:vDvYpOVYxCRQzY9JMye7GlQFGqKHLsjVMg==,iv:+j0WP5gpuowUGtUyjXzkZr+cFXggQH2WtJ6LYtHtEQ8=,tag:xyo9EBkHLrtlwA4pSkAL4A==,type:str]
        optimization:
            vroom:
                host: ENC[AES256_GCM,data:u1HjzdIe+ELnegHrNOahBFfFPcKX,iv:Or00BtFhTG5ImZR+dD+ZkHfwCIdgxF0VsuXBiqNJsoA=,tag:DeilenewBBimbhcASbetLA==,type:str]
s3:
    endpoint: ENC[AES256_GCM,data:RmC6TlXntGeCk4G3LpjBqX4wKy7B,iv:vv/39ezOn0D+DdOQxTbon3YqvFtS8TasCerDv1orzRs=,tag:KYxZEuhESFvliHiMYOC+qQ==,type:str]
    region: ENC[AES256_GCM,data:JImnfiw6VAiR,iv:HtPqr+nYFpdOKZa+TntD0FOoozba008AxarcdwWAgrU=,tag:wV7MUyqQTfUrvBMbQmNFVQ==,type:str]
    use_ssl: ENC[AES256_GCM,data:OvBveQ==,iv:jLToA8lC0L1DozmTUm58spu73TYopZyt+ERd+hHikBs=,tag:IU3Ljzts1KVE6ghQ+2q2rg==,type:bool]
    route-gpx:
        bucket: ENC[AES256_GCM,data:Ku453tNlJs7/hg==,iv:rNWUxYQtB7/qZB9pk7+0dib16DBsmGCKSD80hiR2cWk=,tag:tiaQ96F9SMF8FzWK4VUTJg==,type:str]
        accessKey: ENC[AES256_GCM,data:YCa20Xp145XODA==,iv:ptPKNOdWuEu3CIVl4gUIh8yFQ7UPPM7op07COsnaDgc=,tag:utXMyBBRvT8NcJ8VdDpnuA==,type:str]
        secretAccessKey: ENC[AES256_GCM,data:jSmIImCWH6/2VPymEBRBRG2tDVg7qvhBjWnxIJ8gT2k=,iv:Q/JASJ6oAyR17Xw81aQSaIK2TMEL6XvvOu5zN3hTXv0=,tag:hWnpL+RB+QU/JwVkndgy/A==,type:str]
auth:
    oidc_provider:
        base_url: ENC[AES256_GCM,data:1cmhWJflrmd3PGq4/uk8k/ZdGN59pXwGKllBmCXBMg==,iv:CXPanYFm7lHvHNnQChb/8yzCz/Ox93zHRh/6U13sG/I=,tag:cwW06CVc6swcDkPxhlONEQ==,type:str]
        domain_name: ENC[AES256_GCM,data:94PhVQ0QzGjmP406y/vBy1w9eg==,iv:KG/wak/JjY9j5ShFDDWM6e6Yrs3W+8YcSQa2lXWSxMw=,tag:FINXcn5HmQPuCfoMj2A2ZA==,type:str]
        auth_url: ENC[AES256_GCM,data:K7yofvOKTmF/dgskoX/SM1zJCJe71oF6KgTy4FDzRAOYvncsA9NmkcLY2dVv4EHBsQr7LfJt5/54NLuXdPv+/t0OmlvewUL+9jrqW/0FvPcVVVUxbSjq,iv:4gg5EW76lW0KhxQ/lNBaX5yM7ZpuC8KagXEJ7nPlf4A=,tag:vGR/PK4E7D2qCZ0oSvBkXA==,type:str]
        token_url: ENC[AES256_GCM,data:LV0NmPoJQBKWJk09pOIhtjD3TBRMnjmNSp1tKodpSKm1N5/YugYw6H5X9XxKUT2H4+YyImcSFtKB6ODLK3kzqD9PrFinS0qiw4JfSsX8ho1ZAaZvRHTXvQ==,iv:XLYK7hl1RW6pZ/Il816BK8yynxPhKf0wOPJcCh3X6wQ=,tag:X/mHAGXVhCI5HwwGhwiqXw==,type:str]
        public_key:
            static: ENC[AES256_GCM,data:V7zmfIgipiURlKuJHs+3Yv4g0MyU9R/LBhMwJo16Z8QFM6Ptj0vFohVPNCYIfDR2e9qi6dMrBMAguv/dmnYeZDI3qtuZ1tn94aKUeK8qsdnKLuqH3wdWOIxveTfIZv96Ug5JR+gOWR/SPrwKeLt2HBWxh1LQ/BQ8+hsehkBPQbLyfbNDLpOpG57nFSebKvT5y599zn/RPCOV7PzFemYYSE6Y8IfbbCW+dM80SEu/YJgE+QTRAXfn9i5EXTD2EGHJoQH/ZjW6Wb5vVEelkZ+ZiLV3/T+Tkx5FZgWtE70Etj51qviI/BJBpvxUK0N0JjhDiWT9HwkLwGGPtSIsIPDjeHb0IvOJCmuNQdinJvhpRIAIDo7YiqluWee0zaQbkr9DSns8+UpKo6/aIbEyZmhXnBIP3/0HLFWQ+/Vck1CLCs193opXg206Xv0ObvHRSyMkK9idt6utzfAaJu1UzRbW1CxA2nJ0fnQ5EOul5zjw2+OeppvtB9+GZMcsmv/WhK+YaB9HiLW3XsE=,iv:9BX0V211IxEmoChKR89Re9lsV3/GmUDDVp1kfRMuuhg=,tag:6Kq3qG0W3dV43QUgBnNMaQ==,type:str]
        frontend:
            client_id: ENC[AES256_GCM,data:jZ64/DUl0ICgeq0pRhN9XKO3t8V1d58s,iv:34rQ6Tq6Fm/417U6uQ2osVyg0520c2KejCprNJwbgeM=,tag:YhSIDBKTykhD0VJP8RjPgA==,type:str]
            client_secret: ENC[AES256_GCM,data:YD8NUul61lZfSsVnEO0XDxlcwQxHOeAWYG5Zc2WTsgY=,iv:GRu9KVEuyb24EFnuPBZ4+XE+SRxaxQrNnJstI6CRXG4=,tag:JXlZI7sQSC5lKo1hMgFf7g==,type:str]
        backend:
            client_id: ENC[AES256_GCM,data:zPqE+N2E0pFTeAJpx2fHcNc8sT+xN6k=,iv:1Peg5UoUMZxW+spTjpo0L7C5rY90r2qWKjlDVpW1AWo=,tag:N59lMqFcFn5h9QejRH/1eA==,type:str]
            client_secret: ENC[AES256_GCM,data:u/bIG0rfOoFVp54rBne6dS5D++W5pAcQLtQ7vdgdfZ4=,iv:GeHq2GRi+rnKExAZLdpFRDSqwx6loUx5k3NouUpROfM=,tag:YTBMlSJ/PYnBbSk1qJET/Q==,type:str]
mqtt:
    broker: ENC[AES256_GCM,data:i5q9nN9PtBo39zSN6zXmktXjaS5MArlbw1LrO6sw7/9eYVA=,iv:R6yGnQk9o4GjiJYgopY5hP6dQw9ltys/Rxa+ZBEiFnk=,tag:y1HDo/Ek7z+eHUE/Qk0ZGA==,type:str]
    client_id: ENC[AES256_GCM,data:TZ3GP7yJ5ZQVV+8=,iv:9qUDM2sTKS5hDtXQy509X/h2uUa9Z62iRSsDGtDQPKg=,tag:QtVW/Ot2Ejo+QDVc6jrPUQ==,type:str]
    username: ENC[AES256_GCM,data:4Z1/yOhPzeRPGhEnCh1w7g==,iv:xn1lOLrHDqLzAEWlsSPR0ouYQIVGb6r4dqZHVLbkGvI=,tag:hbrHaKBXD9NRvXrlhR5dhA==,type:str]
    password: ENC[AES256_GCM,data:ctdz3o9Kqkl1MGYhEoRgiLe7KwNhj8WF59wBkeSxjU/pR8iZBob8hgICY+ms1/zBlJGLdsZ9IVJ6EgANitROTANwXIRDwEaTcgNIebjH9jM+0gRFZ+pB98ZYvUTkBwMHl9w=,iv:oVCBCt0/gDEno/S4JPctchAjl7k4nWP7jK3uB4U+q98=,tag:rhLuIKoca/KbeKy+Z2zZxA==,type:str]
    topic: ENC[AES256_GCM,data:vFO1YUkqs8cRk+rPxWvq0oOJSZJ+Wj/vP1aC16jq8cA=,iv:vGkxHTLCzEC6+eyVtLNN2epTj5X4AmoqT80mRfxxqug=,tag:R2SMsUWZppJ1SvQ31Fuhcw==,type:str]
map:
    center:
        - ENC[AES256_GCM,data:sI9ywH2dBV5jgr77UpOCV95F,iv:c0Obi4F+ATZsnUSqNsJZa01O3Es00DtplaO9v3B2LH8=,tag:sfXZnaLvGSqdH/Ye/NOExQ==,type:float]
        - ENC[AES256_GCM,data:Ny2Vql3dmnacNL7w28yEPg==,iv:SRhZ1dHcnh4cV1QEC0o+AvKUsP22joxf0kgfjydNkQY=,tag:PQrKJ9hYm+/koK8H5+6cqA==,type:float]
    bbox:
        - ENC[AES256_GCM,data:lYEx0db21G5s,iv:5YL3mJOIlHQUTV8TyL9IccCbN/Uvx1wRGE5gJ4kSMnU=,tag:FIsqx4eRszwKpE+iN31gaA==,type:float]
        - ENC[AES256_GCM,data:WvwbWhLsBs8=,iv:oe1rRuaz9VpSd4YDVpQHFuEXkA5y4M2MV9yS+sAKJ6k=,tag:JJBGY6/StIRAXBBdYJALog==,type:float]
        - ENC[AES256_GCM,data:K4E7lTqNLyzx,iv:MtAp2y5V7ZUqcS45fmW7NxUrG/5gTa33KrsKXw53oss=,tag:pgfr+Gw5pG3SpQc987TSNQ==,type:float]
        - ENC[AES256_GCM,data:bsre52s8Py8=,iv:/sEURmiAuk0i0R+jyKtn5f/dv9o/1bxX+LXxKZcRwnA=,tag:P59Zf+c1Yosib7GghQKMTQ==,type:float]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuN1BBL3pYb0diRWxNRGFJ
            aVd6RGFQbzNYeHJaTzV0eTZ2MVlKQzJoNWc4ClpCekZ1Sno1aXpCSERSeXBqbkZm
            MHV1d0tnRzBzWDRNY1l1blpBMkh3MzgKLS0tIHAyYUhkSUtjVHNPNWdkTG5lbFRa
            MnBCU1lGUElIYU9YaFhkMnQ1bllsL00Km1bbg7lzOmXjJgRiaazqzGwtKORnYZEx
            WFOv9aKbUKvZzpBw3B8tGeva5sKv543JQMeegDupRxByvQRtFPyEeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-26T18:10:09Z"
    mac: ENC[AES256_GCM,data:3oc/NysrYMWrSCzcMLhjMBTwl6qqosDMddo64TTITwcBL4QlHbY6GD2TXbaCVGGzmDmVZ/jlYjgwK7K/QgXHss1A5u7Yjrz0J9J2ARhGjUYT/NgLnC1g0O+KceGI0f2l3Xf+otYowOyUpJXaD+5NkCIigHLHUtjC0qXJObAiKOo=,iv:QM9iu5WsfRhyPrsyxI+6UB1t+sj//P379dF5VG+kFck=,tag:L8zUWH2vFAYIkcyRhfQ07g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.3
