dashboard:
    title: ENC[AES256_GCM,data:FfSWyYsmW5CzCayufTHaBkiTldVcansMeE0cbdB3zg==,iv:vRaPXec4yBYY2zr91dfLJvMjxVsh7PkV4tf0o+mTL00=,tag:xGsspjB0AAiLiebedhPnjg==,type:str]
server:
    port: ENC[AES256_GCM,data:qSh7Vg==,iv:LN570/W//1b8hsEw2WecCpzaNqmzgsdzj+5lXJTf318=,tag:FhXY+Z1HJEwwaHxNfiwUdg==,type:int]
    development: ENC[AES256_GCM,data:elYzZg==,iv:7fUDz6o4B7GlG+JXrMuPd7w1h3nYnwdqVrQfOlVzsmo=,tag:IPYBaZx5mnMJN/XMS9lQAQ==,type:bool]
    app_url: ENC[AES256_GCM,data:F/s7emDjLbQf92Z8hcm39Fo9pnxx,iv:9uGj+KOgQez1rMmOtzntMLK+/qq/REErJi+UfOJAS40=,tag:50q3h1Kro5AVO7HUutGXbw==,type:str]
    logs:
        level: ENC[AES256_GCM,data:rT15Vf8=,iv:FmhI99bx6TiKWaqhQ1lN36wMi9+ULC7kpIDc4viLp5s=,tag:64482ioKIKlislL+qqrD2Q==,type:str]
        format: ENC[AES256_GCM,data:zn2ZEJoz3w==,iv:yUNSklmR7JgrjDWOm+sv05TZCPeEn0k85zjcSRGq3Ro=,tag:Kd+DdszM68LEkNz5ERFRjg==,type:str]
    database:
        host: ENC[AES256_GCM,data:9LxNDC7dQWiJ,iv:Cv8MEqNN6l+/UwIy1HMvvea2LpE43iKdDmDOUPKjecs=,tag:qH1Leb0uCoiJaI1iUm6wiw==,type:str]
        port: ENC[AES256_GCM,data:2iTrcg==,iv:sx46VGTG6zzjhyTyT5LtGXy7meGz8kXSt61k6WkJzwc=,tag:CzLaezpW6yCh3ZD4K3tfSg==,type:int]
        username: ENC[AES256_GCM,data:F5PUw/AyLnk=,iv:6pOLzW9g+UboXl6P7AGiGqtpop/2uZ9Q47qy6125GCo=,tag:oha4hQU2pKXz17jEUekBTg==,type:str]
        password: ENC[AES256_GCM,data:vKojAFWGu6A=,iv:Lorx9UyKEwq5lZZN1xfh5GEiLdfup2++Ybk8Lt732sw=,tag:OXJu6XjAsMJXAz3kE/f1cg==,type:str]
        name: ENC[AES256_GCM,data:t5AZl2cL6XQ=,iv:KuxfcKHn89It+JUw8ATsb3jkHAKSN9hdSXmP4FexuoM=,tag:g6x60QwiAaJsmRpYxkZf6g==,type:str]
routing:
    start_point:
        - ENC[AES256_GCM,data:c8gUVQ7jCEI35znO/Vqrfx4=,iv:ySLgpBXLRKvL/MTxdxF4Wvhz2MHgpnYS3UhrjxE5FmU=,tag:09hE+Qbut2VqMxy23p5NQw==,type:float]
        - ENC[AES256_GCM,data:wv+82BSurPJN4MvulwGlJbay,iv:bQvv4WncvXTqWlAUL+m5+aXAjk0Qjag1M49T4XuVFsk=,tag:fJfvD5dFW0RHB+f1HIRaUQ==,type:float]
    end_point:
        - ENC[AES256_GCM,data:kaSriLPgOr7owAm8qAOJIsw=,iv:hUFsBthaRbqzK5c5kVluFdLaYxRLhuPbrpm/v9UPhRE=,tag:7gyNwrPRbcf/LJD3E03APQ==,type:float]
        - ENC[AES256_GCM,data:Nt5XQSeI6KirFmdEr/2t8NSd,iv:eADcneMTub+s0ZoTM90PwGhVhRsxE3X91q6rbWjinSA=,tag:lYhS+LAJOaWtqEJD3pHb0g==,type:float]
    watering_point:
        - ENC[AES256_GCM,data:AGvd64SM+rw59cYg/LwjDZc=,iv:J4aEDyfmguXfxNtXSvzERWbLszKy9nP1Nd0hcmpfgOk=,tag:t6ctR0s7viFe1pA18t+DhA==,type:float]
        - ENC[AES256_GCM,data:kqrjL6ztut3GNTCMEUkuIqF6,iv:7BheKbTnxncnFeZx18iWXVLPdmZtfwqsNm4V2caGV0k=,tag:mkR/JWahVdgHk+iiLWG2wA==,type:float]
    valhalla:
        host: ENC[AES256_GCM,data:hnAqJs9TSO58131bS//8hca7/ANf,iv:dXUTwHIJZEbUvrLAqOn+rZdYmF3Xi3hny6oW/A7nYgs=,tag:PDbWog++pngsKnV4/obTrA==,type:str]
        optimization:
            vroom:
                host: ENC[AES256_GCM,data:7QetLcErPBFVOXW0tHgSUv2Mwa/U,iv:LaN46B2XcA5WzVrN3oYgGyd9CjCjiF1uBVy7+5xlfRc=,tag:d1VFW4w4/mg6sOvKX/Cvxg==,type:str]
    ors:
        host: ENC[AES256_GCM,data:dfgWpLaJENGbZnDkNrKwvjRIQk0qq6WmnQ==,iv:qor9rID7P6NYDL+RO3KQ9BAkM6JKGjoj8RYtT2p6z0U=,tag:uKctO4/RlIv6aYWLzKngBQ==,type:str]
        optimization:
            vroom:
                host: ENC[AES256_GCM,data:NJMQfRnZYfkGO7HRQShAaP+oLRq3,iv:LymeuBeZsK0qym10EYyyR8+ug8+qRYeZPUzheok4d6M=,tag:NjPQ/jUCv0F7nSeUxklORQ==,type:str]
s3:
    endpoint: ENC[AES256_GCM,data:+UJZc5Xlhwy03QLjQkdOKdNXJgM9,iv:ayPu+zwFE5sF/+QH+VMCgWY1Klbi/LilIK4xwQnAIwE=,tag:2GqC09utugDhd8IDbKLDcg==,type:str]
    region: ENC[AES256_GCM,data:DGnPH6/0VTrj,iv:EtJmUTIW6YtOyoyr/PP1mZgcjBOzekWZT+CT/55TuGg=,tag:atGBxbtZzMBCh3Spvp8NXw==,type:str]
    use_ssl: ENC[AES256_GCM,data:4/2u6A==,iv:mkt7PMFO57DbrP2QO9bl8SNM1q4bkZgGFlwmi+x7oEg=,tag:RzsOwx0r3O/kHsfyJkV+fw==,type:bool]
    route-gpx:
        bucket: ENC[AES256_GCM,data:Gd0rPUTjzQL+Xw==,iv:67WV5TnajU+pPJymQoArlPKJJtwSxWMQAe3wk8Bd7lY=,tag:V9aIcI9wNaV/je0W8g5Sjw==,type:str]
        accessKey: ENC[AES256_GCM,data:PHuM5YB6wDMXfw==,iv:hLlfsP77QeNMV0Cc13m8WOq/BZeDZCK4E0MlH6tRS8E=,tag:jg+Pd6Uv2z/bfASH0esCYg==,type:str]
        secretAccessKey: ENC[AES256_GCM,data:CLCJVkO0i7RSn5OkFb7uxCPG1KadJCVGoDPfC88xhn0=,iv:JRw1e+50qyMGQlyXymJgIIPHc0RVG1Kzl8T855rUqtQ=,tag:AM3/qVYb0xCYJE0DLbj9Rw==,type:str]
auth:
    oidc_provider:
        base_url: ENC[AES256_GCM,data:iWLVJQiSHF10xN3ZIKCGFFgP38JQrOCrSX43DDgpPQ==,iv:kJlyUs5reuXzp3tSzTGTfJbh1+3xgaU+L+IN3hMfQyM=,tag:LsRAV/oioRXRMWakrEbAVA==,type:str]
        domain_name: ENC[AES256_GCM,data:VsZXM2bEerDSVv+HFEno4vzU3A==,iv:HdIYREV47bWhD7GQlYgOecL/v3rSGNlBpRdo4i/2KwQ=,tag:Ggfj7raa73Wr61ZhitFZuA==,type:str]
        auth_url: ENC[AES256_GCM,data:ctngihDxfUHco0mfbWZ2UA+muTlrxKc4kENpLxYTEvO65TXuTcS8vfYaVToSeXuK6JLx5Ed44qbwlsUTv7BOG2DGCwYqt2bqL9KRzgGOZRwppppGp/jP,iv:NwhaO0RhxWGqXbbhbN3Dz/PzO+5sWWn09jO1GFUSyYw=,tag:zwideQVjJhwa2BRj4K97ow==,type:str]
        token_url: ENC[AES256_GCM,data:0lAD+2KyrgWX5OCgG6Lc7ey44Rzj9iaOY4R/eVD0BmNQz6VOO3KSox/2jEIajBWBVsiCqm7rqVpcZBICZSKuHuVU49+iNhcpKNxGJR2VxtsKkIizST7tkg==,iv:lOuEiucpxNwNBB1fOqO8Wxe03qb1+1rgselvvJ+B9B0=,tag:ZA69RqwnlZnB82yq+1SVqw==,type:str]
        public_key:
            static: ENC[AES256_GCM,data:MKiB4T99iP03r1VMnsT7X1gpjpVsHNug0HzEJckLkr57aO1AMwBNUn4C8GX/nIL3VhHmnKp16WIpM+FZk/jsmEKxzyOuolPxZyT2afip41jOXkHQMvx9fqF3S0mDFmtS+y5dJSDPZ/k88c7j/golQlIMmBFZX6TxLB4EjCe6rO0D3RRZpuzKvP0lS3Rl+D9gEesvqeaL9Ma2vILP72okUn873DYEnoNhSLfVOmDzoe2LNT9MuvdTc6abY5xzmyhfAQ/EuNhVHxkITk7DOXuCWD77qOu0RCGKbAOk5V7WkRVOYxvfKqP4biqo7Zqd2xy2pNZ42OMo9GAQAfFF6hYoevnExDJE8N9JgRhQc6xU8fFOtnhoR0uH326vnj7+jaXcK+ssiFwNmFII1+hbsQLHRQ5MlRDyVS2JVojdH3mEnA6cFe4/5a1jVPZRbRmSp0s7P/skWUokhDW+5/6chQiecggsGF/28AM8RG3D28m+kOmCyD4EilE63FE83f5VQVvJD1Uh/kktdp0=,iv:zOHaPc4H3G/1IryUUFOeyT4zCXBlC7y3swuwstZepIQ=,tag:F3aAf9MQlu75zJZk9v4Izw==,type:str]
        frontend:
            client_id: ENC[AES256_GCM,data:3hIyqkedOBFu2ZkjNV0apK3/xEn+1sMw,iv:YCvYJs8n23JactTixdgyeg3MPDXHYEhohcg9Xe2kH28=,tag:9Tryb0nQM1TerZmDfThiLg==,type:str]
            client_secret: ENC[AES256_GCM,data:TsJ1bghrAqecVWLq4J7PjcJQ1xytFtYQ7xQLf8xG3qk=,iv:nC5b5NPjH5PtQIIa6GGJp3J6N+AR+wpMQIX/YDyZTYE=,tag:eu6HHokigT8eQSa82m48ag==,type:str]
        backend:
            client_id: ENC[AES256_GCM,data:t5T//4dpCFYPY5dNZYMU4ZlTTa6ZZQY=,iv:CQOVdgxJ5VrOv7u2exPhdt0o0Dvjjo2jGRnutA3k/gI=,tag:fH7Lnj3xZmiaiPK7hkioSA==,type:str]
            client_secret: ENC[AES256_GCM,data:cQzrPQcTnTgLnzcODv4euF8gmoNKdOOf44FjjXk/L1M=,iv:3/3gB/prY0EV2pwKC2FgidgRubYrsuPtf5SXr3xIIqc=,tag:RJZ0Hopf8IqTxZ+QNEl5Sg==,type:str]
mqtt:
    broker: ENC[AES256_GCM,data:day0QzxNsh6MwMgHcbhQtpWKRvLTMqErsO9lqxx1+Q28BT4=,iv:RQP1BtXqA0hM1byqgQAW8zbNAsltyXbmwf0K0Jag2/w=,tag:0U/O7kGeieQsC3hCuScn7Q==,type:str]
    client_id: ENC[AES256_GCM,data:Zvlzeu794m8R0Mg=,iv:kGKJNjsAlAbuH913bf2O/FJGixmNe+U4SRWbjmsMPmk=,tag:ElbyTTA6NQxCcMwTE0S08g==,type:str]
    username: ENC[AES256_GCM,data:R99Kj5DGP74MO2+eDIQ/xg==,iv:LNR4tSobCUCVcb/pAQV1BY0kEiRaAnnbtKNrxyxPWVA=,tag:Qvjdu6lGTOue79nG5Jnb2A==,type:str]
    password: ENC[AES256_GCM,data:liow0kDzg5/u/8zmMyEqAcFOSKvMfcK1tJCKSsbzMnFztPFiPFESFC/47hxCTLzgyZCBnfvGXIsITznz3qJljLNVrQQOIVp8qbOLt0l4Glxwp6aPZyMcrEugWonjZTq3HHU=,iv:n/zt7/4hxL/4AzPM97UEtiLE7kxNccupkhfx9K6r7sM=,tag:Xozjdncs5HqQ47tf/iHRgw==,type:str]
    topic: ENC[AES256_GCM,data:HMShHodzwD9c6OdfDHXE02FB4oy0k1bUiCq7LI+GhUPwDE+9E355GZeO,iv:y4WDCQvwZ6IUWtStxNOTFKUJ6M2DPd8hKU0Mruakln0=,tag:Sk6xOhwdz1esbNOpW8edEQ==,type:str]
map:
    center:
        - ENC[AES256_GCM,data:FbURxWHCiGsSp/oxNbuxsN3W,iv:Qip+6v24UGgiB2244uYw7n99F/hN/3spwGzRoop3adU=,tag:TyfI5o16m08TYaJPVDm0iQ==,type:float]
        - ENC[AES256_GCM,data:qetta4KmtO3yygupyoimwA==,iv:Y/+Prm+7jRgNGu/0+1UoGZrXXt0IRnHQ1052atPaMTY=,tag:NJibt4Gmn72B7bYKrNV85w==,type:float]
    bbox:
        - ENC[AES256_GCM,data:svPvCNa1qjKH,iv:1Vrk6QR3iql0r5UYda8AN1J4Jp0TE2OcQIVLrFFTW7Y=,tag:LUEDQxk/Z+gw3ZoalEEifw==,type:float]
        - ENC[AES256_GCM,data:nEqJrxTkrhI=,iv:NyWNqKs//7aYfbaVznNzsXi5CIu3yGgG/RBIv9HSH6c=,tag:knjxeqj1mlnJbQKdXYD29Q==,type:float]
        - ENC[AES256_GCM,data:UFBJV1DymdKp,iv:17jyW5Oa003IbgwLQEEhP/1Dtqe2DQrym0McJNi6CHs=,tag:AM2Ddm6khGSry1Mbk0bdng==,type:float]
        - ENC[AES256_GCM,data:o99DDuyfsmA=,iv:lmJwAgwTK4/F/wjtcNf+hhXbhnoOUA+OGal4m5j5ONY=,tag:cdcfzqQqs48IhNp2a4soBg==,type:float]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZjlldmI4TzM3N0lwMWh0
            QnNKZTZOSUtIb0Jvd3pLTkIzcUVwR3l0YTI0Cks4Wkp2d1pCNkdEZjF5S1NKZVZE
            TVFlKzlzckM0VmFQam9LcHBFOGd0VmcKLS0tIGJaYXF4MUQrNkNiWkcxY3hLRzVH
            MU9NaC9WUWZnNWpvQWJSQzMvU0QxQnMK3L0kScwcs7KWKUJM95I5/wQ7Kd/T2KnZ
            6ayg7Q7KFLhCiSC0xDbR4OLpeAFHOMsDmCP94R2wSNc+7thcQAMQQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-23T13:42:39Z"
    mac: ENC[AES256_GCM,data:lAJ3+u2NzITucb516YtQ7LkAenuamEUJKskgptKMaG4O+tkvVNYlzQw2ifM+8f0sj9ojeUb7wr6d018sq7BPxFrkKOnQE++RWpqAOG3/24xirtgWQnR8PozBfhuFe1l8s7GBtzgaACzBsQxZ0TMOmT5Nynw6KpFMaCkDDyoPvSA=,iv:IhTDxAme8x08VwANrRpoVkDeBqeFDrkrOzekDYsc4Ks=,tag:d8jVZd+dXKMPg9GBfuSl+g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
