dashboard:
    title: ENC[AES256_GCM,data:Aq8XJBbUcUArRemed14JXYLOJUnIGCS5v38gp6Z7lA==,iv:DX5xSFXMzrpHZvbFzRCaaFnfqNqwKcFFpsKMhxB7XOk=,tag:xwjs4cbDZKZ5psOfo83C1Q==,type:str]
server:
    port: ENC[AES256_GCM,data:F9pcyg==,iv:J+VekG6Aw+g4EPv6UYcvz+mGnTvvz3D08/b2ECye4rg=,tag:FVG/bp+fJ4/75M9Wm6vgTQ==,type:int]
    development: ENC[AES256_GCM,data:W5AcNA==,iv:Wx3K5VtCK6Q0a2809AB+aLzaHEUw8tjVTI9gC9RJsig=,tag:gkuX5+Kr78wsPDdqIibhag==,type:bool]
    app_url: ENC[AES256_GCM,data:cY6oI2eVHYYY6MsoCjlc/+5tt3VM,iv:p8gp5JvHp7elEDFzAhm5ym/sZ+4Ku3rPXfsvBr/vMq4=,tag:9sPx8+nXs+jBEgPGYyl2dA==,type:str]
    logs:
        level: ENC[AES256_GCM,data:8GOjLls=,iv:W/NsCzDwMKCJv74TM7UB3T3uLOhDbJ4ZtG4106exc2g=,tag:d/tWPgK/ieZivLDth3nOcA==,type:str]
        format: ENC[AES256_GCM,data:S8Zkfw==,iv:Bk4A/9FmShzdX47vWv5TnZJkon/O2Whcv2qaw66g1u8=,tag:Edc5bhu8rEwHhCyHk4nrjA==,type:str]
    database:
        host: ENC[AES256_GCM,data:zejj25gDNuWE,iv:a424FvUnzHlg9plFj9kkH9Si37EzNsKJr/V7B701aug=,tag:ujKW9l+g3fADQ03nExn2Tg==,type:str]
        port: ENC[AES256_GCM,data:JXb75w==,iv:w0Z5u0EAAzPvlIBVmMOTySvCL+ilBOPARXeQlxe1Wno=,tag:6TUAhR/iC566vahPZ6xzhA==,type:int]
        username: ENC[AES256_GCM,data:Zj6/vqViHuE=,iv:U/NKqpQJFcp3PYp8Ch/FtJnTL6w3HTNvchaKXaS6W3Q=,tag:eTbaaNGRX78IeYz7h+r0pA==,type:str]
        password: ENC[AES256_GCM,data:vsIYpIx8qY8=,iv:jE9VrOuBBVfvPsmx48sNyPHzpoNU7balBYd0i8zM+xU=,tag:Im9xvE3XEpektN9vblfmQQ==,type:str]
        name: ENC[AES256_GCM,data:4WxFHQyOa6g=,iv:cL7TC3/TTq/Cfblpw/l3chiZQ0ujtZBHWmOanYzhkHw=,tag:w47xhp16YymZLuG57uFSiQ==,type:str]
routing:
    start_point:
        - ENC[AES256_GCM,data:zaNTFFq3yVppF4t68pc7Beg=,iv:Cgabeefuf+VOrghyML5tfbHodIzc+6IZqILx9hSStvw=,tag:qzsBPGPSCbfYuoR6uHqQdQ==,type:float]
        - ENC[AES256_GCM,data:ZIRJ4nop74RQIcPe0roRcFBL,iv:ekQr3hzoaQ7CgmrlNz1BYvGltnHEZiN0deR28ijGAd4=,tag:DRS67eWfswcpqXVByB23NA==,type:float]
    end_point:
        - ENC[AES256_GCM,data:C8N2RtI+YmIFvg4kaQVCSM8=,iv:5vVy4G/bXGeETUhGwt93Vak0jQkrXBzOiRQt3zhQ3iA=,tag:+tsNkFd4nHZeyU3YpdUmlw==,type:float]
        - ENC[AES256_GCM,data:U2fceDNS7I3QHeyA1P4euPeM,iv:HjAVoT4NJKGIejJQ76M47WCym0ptUYiRE8FAZU/0neU=,tag:4KnLqnXdkbZs1zj/G4b/Zg==,type:float]
    watering_point:
        - ENC[AES256_GCM,data:yvt+fEnxsJGmpg7d4P+vI+g=,iv:IssE3F+KHV3DR61a52SIN5/W0E45/506p4E0VRjwJr0=,tag:QLmVZaKq+S5hGOBs+wby0Q==,type:float]
        - ENC[AES256_GCM,data:l3dPv81tP8SV95kt/QJtlAnC,iv:MRerCGeG/nTU2TcQTdRR+vFVM0hULHs3EPNku6nh9cM=,tag:4UEkjHnA/QwLcwjqnQgtAQ==,type:float]
    valhalla:
        host: ENC[AES256_GCM,data:HCrDLxOU70T6jVCovv41jGb4kTFu,iv:0LxzpHx/wWMl5EV/J+5ejD18hrs35exZsOQC6GgYKCc=,tag:BI/Krx/NP00qvFOnGKr/5A==,type:str]
        optimization:
            vroom:
                host: ENC[AES256_GCM,data:cXlah67ARy+mELjHwgCIUFRPKXy/,iv:EZXianS0r5wJ1YFc5iod/yugi2jy6WvfBSwne5dvyxk=,tag:RfIuYtO5Fx3DKJDo2BQtOA==,type:str]
    ors:
        host: ENC[AES256_GCM,data:fFiuLg+crUgEHs5z9b5kk5myMjy0JEJMTg==,iv:OJCJKrsJ8StGkkTHZb8fyht/AUbLPovSlUhDG5WOLsA=,tag:0wqnAlQLjFNjqkoQ61ECoA==,type:str]
        optimization:
            vroom:
                host: ENC[AES256_GCM,data:B3xyvbJjdm+HUCOVRJmUm9EjnDni,iv:Pt7uVhMO05DIDLO88KoSDaxfGcm20tLatOWRioQAg08=,tag:Y+OWu6+UVY4T/q//XK78og==,type:str]
s3:
    endpoint: ENC[AES256_GCM,data:oZdSKCYvH8xMuE+CWPYkQ2EMtXcH,iv:0EKoVWZZwGDl/kN6vY3E/4EpuSOXZa9zY2mSKsX+Sw4=,tag:dYXZmLs2kuiz4rIk8fwq5A==,type:str]
    region: ENC[AES256_GCM,data:FuwsaA3B2ZXo,iv:5+9ZOl9FdzWvmHWqWGEElib36DKb2N56fy5b6MeIyM4=,tag:VSL+ETlOwZ8COnwSDoRT/w==,type:str]
    use_ssl: ENC[AES256_GCM,data:Xesc3A==,iv:mdBtfgQNostKPhBqWEkCKqvtgdBzSutcN6cL9nExIPI=,tag:YvpCtQO2v+Sys57AT5gHSA==,type:bool]
    route-gpx:
        bucket: ENC[AES256_GCM,data:07sU4XhGjHMGkQ==,iv:Z7MdtEacApB9hpjTZwvJgxq/J5aQrOWbhuKOrxxcLZw=,tag:v8dr/g3zHQVIq4c8RAa82A==,type:str]
        accessKey: ENC[AES256_GCM,data:XWWbf7gRGXiVVw==,iv:ZEZgoBT8ZHRIbIMke4s5VSwdmysZvuRm+NKCX0ew/tY=,tag:QA8f5wPKCIjB5DfpZwf6KA==,type:str]
        secretAccessKey: ENC[AES256_GCM,data:q6MKSKQ5+UYUOvQTkC8Dy05n68gcOhlc12rO3qfTJ04=,iv:gWwpN7Cthk3WOOsPiPp8xSHGs1cgDaPWG40O/PAHTS4=,tag:87kGeWVIutuTBMjzqY5ycA==,type:str]
auth:
    oidc_provider:
        base_url: ENC[AES256_GCM,data:02DAllOPKYA9qrsEBL1Or19SS6paDxjcxR14FM1w1w==,iv:14i+gRemxPnsdQiEaofbdXjxfW/eOV6MGNdeQHsWJsA=,tag:6SCO9wZwrGlv02YHfpjPVw==,type:str]
        domain_name: ENC[AES256_GCM,data:90hCF77m4pmw0arArp1gQFGOdQ==,iv:2fk8Kk7gTPVg31DPakBBrZ/1mhanqJVFozs+T8V+HPs=,tag:bVFluuW+B2qMDOxJXWGlfA==,type:str]
        auth_url: ENC[AES256_GCM,data:vsWP1Tr0rW9EVoClzODS12z74fDIeCoZx5b/DCOGcnN721LfYZarGQgaGeA4dMYThMFmAcOeG6L4LzVQBrCeBUOWyU52HwXj6zlmbCwR3TnjonSsZNY/,iv:rdW+cFJfHIQNHmr8vFq7pN6+ishYahEguSeMV8oCqbE=,tag:mIYYj/DM1CmPu/pJmDf+7g==,type:str]
        token_url: ENC[AES256_GCM,data:faT2qhcIqmyJoHFMT7Dwi9bwhleXYUOPo1plpVvetQnoKXxVVqKKQDF73TZFIIkqABPZ6tYDMPHa8YWpYK1zLeNQd9/hd72WNsANmQNzA/Mt0KYX0wa8pA==,iv:rjwAdGFaxodncdBLFp7/XUicPypstET6mAmmw7R1Xyk=,tag:JLYBo+0izI+X+N6yWNo0DQ==,type:str]
        public_key:
            static: ENC[AES256_GCM,data:ZpSm1qqryn27+977y0IQzdfxK2BUmGpQrJr4/IzYdhZIOcV4lGrZoHg0vwTLRpMz4foyO4ijXzvHP2SiSgdH9IcJw4HlRh7+uCDgeDUe13Q/uGwPFt0s1vKe92ZGyGT0d6jxr/m6y1u7oxRlM4MunlCS+rT1q9ZldRj3ZeGHpEJOGcsHeaQFeWJ1B8MT88YgvaNTKOzL/ck3/RmpEbAN1R0B9chVvmL9LaFe1fCx8/77RZbpidqdAUqunSezqhNO19u9vlSm4KF2DWCRGzot1suPEZDDy/ftGiyZ/IVjYagxLbpZrb11M86qz1ars3D7YmcnUwmmkNJTbAakAIDcRbqLP5MYkmx4VcxlhYFzjqvdqdBhvkqQlgpR7E2I1npY+vCARJsditmqeN6161T+A/1ufiUPg/uhBecZP8JutzwFCPrRXIs/S6u6N4fKWaOpDJyeYaS0BbysStBjgJlgQ99JUVtX4efpezDMEWlY2mU4HNOWIG/xdGj059CfPm+5jOIk9f9HKho=,iv:/okevcKu38i8JfkZPbwvk7jDNoKWwTxnZZdRW8+5z+Q=,tag:7X3AxxgztTgDuKKKutP1ag==,type:str]
        frontend:
            client_id: ENC[AES256_GCM,data:MwfLwvLu2hSQBIRyw1cGhueDOyjj2NTj,iv:xzN85wAPn7IXkbzM9uAaL9mIEgdmtfXIR1lxBr0idKQ=,tag:mBBtBUXBOAaAG6ovMZJF9g==,type:str]
            client_secret: ENC[AES256_GCM,data:eROp0aaPXX0GooHcrYL4FOx4+7drhv4iuvZPdqBIXK0=,iv:ai/uprRLxAv2XWOwmoAhV/YoZ2l5mtm+wPuuHwYUE0I=,tag:HpkR1CjKtkQdeld6iO3NHQ==,type:str]
        backend:
            client_id: ENC[AES256_GCM,data:xOoxoBOs47kSMvBb0iOUKNX7wypzhE8=,iv:FWokZqCG8LiMpSA1OQCOLr1rziAnOCrZQLAycAuRaRE=,tag:0i8RJRw1BShTZ45i+y5lXQ==,type:str]
            client_secret: ENC[AES256_GCM,data:WUku0I9j+Hat7LFQEisMPt79e78OFzLhzCF2wM5k6og=,iv:zMKJiyAaBq9LP0fuUXGcg7PuhBDnO/6VUWQq7k8/0y0=,tag:1J+Sub4OA2bL0LfDiXvLtA==,type:str]
mqtt:
    broker: ENC[AES256_GCM,data:xRJ8h30ixdLnWBy3S90qNdtbdRmnz5V/z4N/4tVgBFhVjaE=,iv:CjWE388fPIsin35X7d4phP7a+0tyjBHNvegfTgaYN6w=,tag:0MH8vYtm0eqGGPpVvl8p7g==,type:str]
    client_id: ENC[AES256_GCM,data:at9yzqnf+oEyWRY=,iv:ACoeiDk3240JO4ff3f4tiqTP0FbYrkYTCv7HTFc/aW0=,tag:khiuFpzNO7HUerass/fY2Q==,type:str]
    username: ENC[AES256_GCM,data:+5OqW9NE4QZXq9f3tefu6g==,iv:a6jcOfsbupTLVRiB4KnY1RSP5jRnUTxnIJl+4Vf73fg=,tag:YYGmfTUKuxeQIjvr8dpfeQ==,type:str]
    password: ENC[AES256_GCM,data:2mA8sWPDOG6R3aFtGv0+EnLKbE+d89UpXuNGFTfh6Npxja5k6sAi64/Qg89AqcfkAhopJrai/tAIZtymQb2U6WD7mWSIvNkmhMfLyclaGS6rGAphHf/QZ8f7w2lJoRawfEY=,iv:gmi2Z34DIVkuqmduVb6d85LoJmb6VkTrOD4U7xmILCI=,tag:ZD2jge9/nCH8VLFZaxv1cg==,type:str]
    topic: ENC[AES256_GCM,data:nyXH7qR87rpGSunxfhYA3LAxSO0c8o0NO/sIR/zZoLLyDmGQ0IL7SWkp,iv:1bJpdezGfMwFc6Tpm6s0HIC8dpFVMcFtiaTFn/OKA34=,tag:ZaauF+MLrzVUAElAZ4RUyg==,type:str]
map:
    center:
        - ENC[AES256_GCM,data:HdoMEF2RzMl09SVtSRxmddln,iv:Mmeqr94wA7m9twEY387p0IT47xLWXCRSpYbJnuLqwSo=,tag:iX/hMQSskgvkYrRQad1W3w==,type:float]
        - ENC[AES256_GCM,data:xcBGn5tf8NdIun3NoqioFw==,iv:6Ae44z09UEA3YG/oXkC7xH2tgqTzOFvh7f20qXswnRA=,tag:4OcVYmIC+c0Ou1HwRTbrJg==,type:float]
    bbox:
        - ENC[AES256_GCM,data:FP18vf0=,iv:XT5d30hDESRs3Rptd8rjxnKfY9xesXVQS04lRVKSgyI=,tag:lMctF07mY1XS0dCmtr/sQw==,type:float]
        - ENC[AES256_GCM,data:lHq8,iv:x5/VY5lGxXtDQqD2o9yobr/LjcRZadkEHKFJqE9toZ8=,tag:OQsoNbh2Px0LdA4VutkuRA==,type:float]
        - ENC[AES256_GCM,data:xo1zOE4=,iv:Hx48/xly7+zsCO8mHnIviWm+Gj3dVCzImyaUuSDk+UU=,tag:kWx0Csq/a7PZEPhkX/4qAw==,type:float]
        - ENC[AES256_GCM,data:5/3J,iv:jZaA3zTYTUUQxdrtyY6HzME6ZP9jW+Zfs7AGSU+O0ag=,tag:IBoV7njEYClXtVgpI7VUaw==,type:float]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHcFRoMHc3Y1NTZ3FCcVBa
            ajZqcU0rVngvWXdpb20yUVhUclB5SEZGclI0CmhPbTNEMHdrQ1Y0bk0xdlFNVlNz
            N0JmeE8rc09yN3pnNzVFU0hKYnRxSXMKLS0tIENWcFl4M1pMUXRKeUtCb2ZxdUVu
            RkdHU2lnZ3lWYUhhdE5Pa0VGeERIY3MKCEBoPQye2dGeMT4LftN3tMlUExeG8k1n
            M2H5blHYIep/r+gTksKUTRPYpHH9B105wNcmQ0WyVSTcUcLjeWYmvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-16T15:54:57Z"
    mac: ENC[AES256_GCM,data:00zvLTGiQm2ekUyPBI0oeLpLHBMkmTbcrtvcpzeZoQ2vzOmmGRcO+yRMQTtq+5ZroaeQNo636JQPymZw1e4TfiPvLiTvaTxbFbVX+7AGSqOVv2DmhyMIW7AByEMcwxmBbjRQGUe5TrRuE+mIvX8nWb+zwoJjHAk1nYBCbwbW7/I=,iv:1QRaoJhAuiEK4vsXz/jZ8tfk7mGVPB4Q8pveG5NwgZQ=,tag:eCiUqNoqkrEMWz5/Nb+v5w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
