/*
Green Space Management API

Testing SensorAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package client

import (
	"context"
	openapiclient "github.com/green-ecolution/green-ecolution-backend/pkg/client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_client_SensorAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SensorAPIService DeleteSensor", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var sensorId string

		httpRes, err := apiClient.SensorAPI.DeleteSensor(context.Background(), sensorId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SensorAPIService GetAllSensorDataById", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var sensorId string

		resp, httpRes, err := apiClient.SensorAPI.GetAllSensorDataById(context.Background(), sensorId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SensorAPIService GetAllSensors", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.SensorAPI.GetAllSensors(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SensorAPIService GetSensorById", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var sensorId string

		resp, httpRes, err := apiClient.SensorAPI.GetSensorById(context.Background(), sensorId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
