/*
Openrouteservice

Testing IsochronesServiceAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package ors

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/green-ecolution/green-ecolution-backend/ors"
)

func Test_ors_IsochronesServiceAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test IsochronesServiceAPIService GetDefaultIsochrones", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var profile string

		resp, httpRes, err := apiClient.IsochronesServiceAPI.GetDefaultIsochrones(context.Background(), profile).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
