/*
Openrouteservice

Testing HealthServiceAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package ors

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/green-ecolution/green-ecolution-backend/ors"
)

func Test_ors_HealthServiceAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test HealthServiceAPIService FetchHealth", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.HealthServiceAPI.FetchHealth(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
