/*
Green Space Management API

This is the API for the Green Ecolution Management System.

API version: develop
Contact: info@green-ecolution.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the WateringPlan type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WateringPlan{}

// WateringPlan struct for WateringPlan
type WateringPlan struct {
	AdditionalInformation map[string]interface{}     `json:"additional_information,omitempty"`
	CancellationNote      string                     `json:"cancellation_note"`
	CreatedAt             string                     `json:"created_at"`
	Date                  string                     `json:"date"`
	Description           string                     `json:"description"`
	Distance              float32                    `json:"distance"`
	Duration              float32                    `json:"duration"`
	Evaluation            []EntitiesEvaluationValue  `json:"evaluation"`
	GpxUrl                string                     `json:"gpx_url"`
	Id                    int32                      `json:"id"`
	Provider              string                     `json:"provider"`
	RefillCount           int32                      `json:"refill_count"`
	Status                EntitiesWateringPlanStatus `json:"status"`
	TotalWaterRequired    float32                    `json:"total_water_required"`
	Trailer               *Vehicle                   `json:"trailer,omitempty"`
	Transporter           Vehicle                    `json:"transporter"`
	Treeclusters          []TreeClusterInList        `json:"treeclusters"`
	UpdatedAt             string                     `json:"updated_at"`
	UserIds               []string                   `json:"user_ids"`
}

type _WateringPlan WateringPlan

// NewWateringPlan instantiates a new WateringPlan object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWateringPlan(cancellationNote string, createdAt string, date string, description string, distance float32, duration float32, evaluation []EntitiesEvaluationValue, gpxUrl string, id int32, provider string, refillCount int32, status EntitiesWateringPlanStatus, totalWaterRequired float32, transporter Vehicle, treeclusters []TreeClusterInList, updatedAt string, userIds []string) *WateringPlan {
	this := WateringPlan{}
	this.CancellationNote = cancellationNote
	this.CreatedAt = createdAt
	this.Date = date
	this.Description = description
	this.Distance = distance
	this.Duration = duration
	this.Evaluation = evaluation
	this.GpxUrl = gpxUrl
	this.Id = id
	this.Provider = provider
	this.RefillCount = refillCount
	this.Status = status
	this.TotalWaterRequired = totalWaterRequired
	this.Transporter = transporter
	this.Treeclusters = treeclusters
	this.UpdatedAt = updatedAt
	this.UserIds = userIds
	return &this
}

// NewWateringPlanWithDefaults instantiates a new WateringPlan object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWateringPlanWithDefaults() *WateringPlan {
	this := WateringPlan{}
	return &this
}

// GetAdditionalInformation returns the AdditionalInformation field value if set, zero value otherwise.
func (o *WateringPlan) GetAdditionalInformation() map[string]interface{} {
	if o == nil || IsNil(o.AdditionalInformation) {
		var ret map[string]interface{}
		return ret
	}
	return o.AdditionalInformation
}

// GetAdditionalInformationOk returns a tuple with the AdditionalInformation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WateringPlan) GetAdditionalInformationOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.AdditionalInformation) {
		return map[string]interface{}{}, false
	}
	return o.AdditionalInformation, true
}

// HasAdditionalInformation returns a boolean if a field has been set.
func (o *WateringPlan) HasAdditionalInformation() bool {
	if o != nil && !IsNil(o.AdditionalInformation) {
		return true
	}

	return false
}

// SetAdditionalInformation gets a reference to the given map[string]interface{} and assigns it to the AdditionalInformation field.
func (o *WateringPlan) SetAdditionalInformation(v map[string]interface{}) {
	o.AdditionalInformation = v
}

// GetCancellationNote returns the CancellationNote field value
func (o *WateringPlan) GetCancellationNote() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CancellationNote
}

// GetCancellationNoteOk returns a tuple with the CancellationNote field value
// and a boolean to check if the value has been set.
func (o *WateringPlan) GetCancellationNoteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CancellationNote, true
}

// SetCancellationNote sets field value
func (o *WateringPlan) SetCancellationNote(v string) {
	o.CancellationNote = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *WateringPlan) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *WateringPlan) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *WateringPlan) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetDate returns the Date field value
func (o *WateringPlan) GetDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *WateringPlan) GetDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *WateringPlan) SetDate(v string) {
	o.Date = v
}

// GetDescription returns the Description field value
func (o *WateringPlan) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *WateringPlan) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *WateringPlan) SetDescription(v string) {
	o.Description = v
}

// GetDistance returns the Distance field value
func (o *WateringPlan) GetDistance() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Distance
}

// GetDistanceOk returns a tuple with the Distance field value
// and a boolean to check if the value has been set.
func (o *WateringPlan) GetDistanceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Distance, true
}

// SetDistance sets field value
func (o *WateringPlan) SetDistance(v float32) {
	o.Distance = v
}

// GetDuration returns the Duration field value
func (o *WateringPlan) GetDuration() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Duration
}

// GetDurationOk returns a tuple with the Duration field value
// and a boolean to check if the value has been set.
func (o *WateringPlan) GetDurationOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Duration, true
}

// SetDuration sets field value
func (o *WateringPlan) SetDuration(v float32) {
	o.Duration = v
}

// GetEvaluation returns the Evaluation field value
func (o *WateringPlan) GetEvaluation() []EntitiesEvaluationValue {
	if o == nil {
		var ret []EntitiesEvaluationValue
		return ret
	}

	return o.Evaluation
}

// GetEvaluationOk returns a tuple with the Evaluation field value
// and a boolean to check if the value has been set.
func (o *WateringPlan) GetEvaluationOk() ([]EntitiesEvaluationValue, bool) {
	if o == nil {
		return nil, false
	}
	return o.Evaluation, true
}

// SetEvaluation sets field value
func (o *WateringPlan) SetEvaluation(v []EntitiesEvaluationValue) {
	o.Evaluation = v
}

// GetGpxUrl returns the GpxUrl field value
func (o *WateringPlan) GetGpxUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GpxUrl
}

// GetGpxUrlOk returns a tuple with the GpxUrl field value
// and a boolean to check if the value has been set.
func (o *WateringPlan) GetGpxUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GpxUrl, true
}

// SetGpxUrl sets field value
func (o *WateringPlan) SetGpxUrl(v string) {
	o.GpxUrl = v
}

// GetId returns the Id field value
func (o *WateringPlan) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WateringPlan) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WateringPlan) SetId(v int32) {
	o.Id = v
}

// GetProvider returns the Provider field value
func (o *WateringPlan) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *WateringPlan) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *WateringPlan) SetProvider(v string) {
	o.Provider = v
}

// GetRefillCount returns the RefillCount field value
func (o *WateringPlan) GetRefillCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RefillCount
}

// GetRefillCountOk returns a tuple with the RefillCount field value
// and a boolean to check if the value has been set.
func (o *WateringPlan) GetRefillCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RefillCount, true
}

// SetRefillCount sets field value
func (o *WateringPlan) SetRefillCount(v int32) {
	o.RefillCount = v
}

// GetStatus returns the Status field value
func (o *WateringPlan) GetStatus() EntitiesWateringPlanStatus {
	if o == nil {
		var ret EntitiesWateringPlanStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *WateringPlan) GetStatusOk() (*EntitiesWateringPlanStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *WateringPlan) SetStatus(v EntitiesWateringPlanStatus) {
	o.Status = v
}

// GetTotalWaterRequired returns the TotalWaterRequired field value
func (o *WateringPlan) GetTotalWaterRequired() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TotalWaterRequired
}

// GetTotalWaterRequiredOk returns a tuple with the TotalWaterRequired field value
// and a boolean to check if the value has been set.
func (o *WateringPlan) GetTotalWaterRequiredOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalWaterRequired, true
}

// SetTotalWaterRequired sets field value
func (o *WateringPlan) SetTotalWaterRequired(v float32) {
	o.TotalWaterRequired = v
}

// GetTrailer returns the Trailer field value if set, zero value otherwise.
func (o *WateringPlan) GetTrailer() Vehicle {
	if o == nil || IsNil(o.Trailer) {
		var ret Vehicle
		return ret
	}
	return *o.Trailer
}

// GetTrailerOk returns a tuple with the Trailer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WateringPlan) GetTrailerOk() (*Vehicle, bool) {
	if o == nil || IsNil(o.Trailer) {
		return nil, false
	}
	return o.Trailer, true
}

// HasTrailer returns a boolean if a field has been set.
func (o *WateringPlan) HasTrailer() bool {
	if o != nil && !IsNil(o.Trailer) {
		return true
	}

	return false
}

// SetTrailer gets a reference to the given Vehicle and assigns it to the Trailer field.
func (o *WateringPlan) SetTrailer(v Vehicle) {
	o.Trailer = &v
}

// GetTransporter returns the Transporter field value
func (o *WateringPlan) GetTransporter() Vehicle {
	if o == nil {
		var ret Vehicle
		return ret
	}

	return o.Transporter
}

// GetTransporterOk returns a tuple with the Transporter field value
// and a boolean to check if the value has been set.
func (o *WateringPlan) GetTransporterOk() (*Vehicle, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Transporter, true
}

// SetTransporter sets field value
func (o *WateringPlan) SetTransporter(v Vehicle) {
	o.Transporter = v
}

// GetTreeclusters returns the Treeclusters field value
func (o *WateringPlan) GetTreeclusters() []TreeClusterInList {
	if o == nil {
		var ret []TreeClusterInList
		return ret
	}

	return o.Treeclusters
}

// GetTreeclustersOk returns a tuple with the Treeclusters field value
// and a boolean to check if the value has been set.
func (o *WateringPlan) GetTreeclustersOk() ([]TreeClusterInList, bool) {
	if o == nil {
		return nil, false
	}
	return o.Treeclusters, true
}

// SetTreeclusters sets field value
func (o *WateringPlan) SetTreeclusters(v []TreeClusterInList) {
	o.Treeclusters = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *WateringPlan) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *WateringPlan) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *WateringPlan) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

// GetUserIds returns the UserIds field value
func (o *WateringPlan) GetUserIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.UserIds
}

// GetUserIdsOk returns a tuple with the UserIds field value
// and a boolean to check if the value has been set.
func (o *WateringPlan) GetUserIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserIds, true
}

// SetUserIds sets field value
func (o *WateringPlan) SetUserIds(v []string) {
	o.UserIds = v
}

func (o WateringPlan) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WateringPlan) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AdditionalInformation) {
		toSerialize["additional_information"] = o.AdditionalInformation
	}
	toSerialize["cancellation_note"] = o.CancellationNote
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["date"] = o.Date
	toSerialize["description"] = o.Description
	toSerialize["distance"] = o.Distance
	toSerialize["duration"] = o.Duration
	toSerialize["evaluation"] = o.Evaluation
	toSerialize["gpx_url"] = o.GpxUrl
	toSerialize["id"] = o.Id
	toSerialize["provider"] = o.Provider
	toSerialize["refill_count"] = o.RefillCount
	toSerialize["status"] = o.Status
	toSerialize["total_water_required"] = o.TotalWaterRequired
	if !IsNil(o.Trailer) {
		toSerialize["trailer"] = o.Trailer
	}
	toSerialize["transporter"] = o.Transporter
	toSerialize["treeclusters"] = o.Treeclusters
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["user_ids"] = o.UserIds
	return toSerialize, nil
}

func (o *WateringPlan) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cancellation_note",
		"created_at",
		"date",
		"description",
		"distance",
		"duration",
		"evaluation",
		"gpx_url",
		"id",
		"provider",
		"refill_count",
		"status",
		"total_water_required",
		"transporter",
		"treeclusters",
		"updated_at",
		"user_ids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWateringPlan := _WateringPlan{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWateringPlan)

	if err != nil {
		return err
	}

	*o = WateringPlan(varWateringPlan)

	return err
}

type NullableWateringPlan struct {
	value *WateringPlan
	isSet bool
}

func (v NullableWateringPlan) Get() *WateringPlan {
	return v.value
}

func (v *NullableWateringPlan) Set(val *WateringPlan) {
	v.value = val
	v.isSet = true
}

func (v NullableWateringPlan) IsSet() bool {
	return v.isSet
}

func (v *NullableWateringPlan) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWateringPlan(val *WateringPlan) *NullableWateringPlan {
	return &NullableWateringPlan{value: val, isSet: true}
}

func (v NullableWateringPlan) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWateringPlan) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
