/*
Green Space Management API

This is the API for the Green Ecolution Management System.

API version: develop
Contact: info@green-ecolution.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the EntitiesGeoJSONMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntitiesGeoJSONMetadata{}

// EntitiesGeoJSONMetadata struct for EntitiesGeoJSONMetadata
type EntitiesGeoJSONMetadata struct {
	EndPoint      *EntitiesGeoJSONLocation `json:"endPoint,omitempty"`
	StartPoint    *EntitiesGeoJSONLocation `json:"startPoint,omitempty"`
	WateringPoint *EntitiesGeoJSONLocation `json:"wateringPoint,omitempty"`
}

// NewEntitiesGeoJSONMetadata instantiates a new EntitiesGeoJSONMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntitiesGeoJSONMetadata() *EntitiesGeoJSONMetadata {
	this := EntitiesGeoJSONMetadata{}
	return &this
}

// NewEntitiesGeoJSONMetadataWithDefaults instantiates a new EntitiesGeoJSONMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntitiesGeoJSONMetadataWithDefaults() *EntitiesGeoJSONMetadata {
	this := EntitiesGeoJSONMetadata{}
	return &this
}

// GetEndPoint returns the EndPoint field value if set, zero value otherwise.
func (o *EntitiesGeoJSONMetadata) GetEndPoint() EntitiesGeoJSONLocation {
	if o == nil || IsNil(o.EndPoint) {
		var ret EntitiesGeoJSONLocation
		return ret
	}
	return *o.EndPoint
}

// GetEndPointOk returns a tuple with the EndPoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntitiesGeoJSONMetadata) GetEndPointOk() (*EntitiesGeoJSONLocation, bool) {
	if o == nil || IsNil(o.EndPoint) {
		return nil, false
	}
	return o.EndPoint, true
}

// HasEndPoint returns a boolean if a field has been set.
func (o *EntitiesGeoJSONMetadata) HasEndPoint() bool {
	if o != nil && !IsNil(o.EndPoint) {
		return true
	}

	return false
}

// SetEndPoint gets a reference to the given EntitiesGeoJSONLocation and assigns it to the EndPoint field.
func (o *EntitiesGeoJSONMetadata) SetEndPoint(v EntitiesGeoJSONLocation) {
	o.EndPoint = &v
}

// GetStartPoint returns the StartPoint field value if set, zero value otherwise.
func (o *EntitiesGeoJSONMetadata) GetStartPoint() EntitiesGeoJSONLocation {
	if o == nil || IsNil(o.StartPoint) {
		var ret EntitiesGeoJSONLocation
		return ret
	}
	return *o.StartPoint
}

// GetStartPointOk returns a tuple with the StartPoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntitiesGeoJSONMetadata) GetStartPointOk() (*EntitiesGeoJSONLocation, bool) {
	if o == nil || IsNil(o.StartPoint) {
		return nil, false
	}
	return o.StartPoint, true
}

// HasStartPoint returns a boolean if a field has been set.
func (o *EntitiesGeoJSONMetadata) HasStartPoint() bool {
	if o != nil && !IsNil(o.StartPoint) {
		return true
	}

	return false
}

// SetStartPoint gets a reference to the given EntitiesGeoJSONLocation and assigns it to the StartPoint field.
func (o *EntitiesGeoJSONMetadata) SetStartPoint(v EntitiesGeoJSONLocation) {
	o.StartPoint = &v
}

// GetWateringPoint returns the WateringPoint field value if set, zero value otherwise.
func (o *EntitiesGeoJSONMetadata) GetWateringPoint() EntitiesGeoJSONLocation {
	if o == nil || IsNil(o.WateringPoint) {
		var ret EntitiesGeoJSONLocation
		return ret
	}
	return *o.WateringPoint
}

// GetWateringPointOk returns a tuple with the WateringPoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntitiesGeoJSONMetadata) GetWateringPointOk() (*EntitiesGeoJSONLocation, bool) {
	if o == nil || IsNil(o.WateringPoint) {
		return nil, false
	}
	return o.WateringPoint, true
}

// HasWateringPoint returns a boolean if a field has been set.
func (o *EntitiesGeoJSONMetadata) HasWateringPoint() bool {
	if o != nil && !IsNil(o.WateringPoint) {
		return true
	}

	return false
}

// SetWateringPoint gets a reference to the given EntitiesGeoJSONLocation and assigns it to the WateringPoint field.
func (o *EntitiesGeoJSONMetadata) SetWateringPoint(v EntitiesGeoJSONLocation) {
	o.WateringPoint = &v
}

func (o EntitiesGeoJSONMetadata) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntitiesGeoJSONMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EndPoint) {
		toSerialize["endPoint"] = o.EndPoint
	}
	if !IsNil(o.StartPoint) {
		toSerialize["startPoint"] = o.StartPoint
	}
	if !IsNil(o.WateringPoint) {
		toSerialize["wateringPoint"] = o.WateringPoint
	}
	return toSerialize, nil
}

type NullableEntitiesGeoJSONMetadata struct {
	value *EntitiesGeoJSONMetadata
	isSet bool
}

func (v NullableEntitiesGeoJSONMetadata) Get() *EntitiesGeoJSONMetadata {
	return v.value
}

func (v *NullableEntitiesGeoJSONMetadata) Set(val *EntitiesGeoJSONMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableEntitiesGeoJSONMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableEntitiesGeoJSONMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntitiesGeoJSONMetadata(val *EntitiesGeoJSONMetadata) *NullableEntitiesGeoJSONMetadata {
	return &NullableEntitiesGeoJSONMetadata{value: val, isSet: true}
}

func (v NullableEntitiesGeoJSONMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntitiesGeoJSONMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
