/*
Green Space Management API

This is the API for the Green Ecolution Management System.

API version: develop
Contact: info@green-ecolution.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SensorList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SensorList{}

// SensorList struct for SensorList
type SensorList struct {
	Data       []Sensor   `json:"data"`
	Pagination Pagination `json:"pagination"`
}

type _SensorList SensorList

// NewSensorList instantiates a new SensorList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSensorList(data []Sensor, pagination Pagination) *SensorList {
	this := SensorList{}
	this.Data = data
	this.Pagination = pagination
	return &this
}

// NewSensorListWithDefaults instantiates a new SensorList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSensorListWithDefaults() *SensorList {
	this := SensorList{}
	return &this
}

// GetData returns the Data field value
func (o *SensorList) GetData() []Sensor {
	if o == nil {
		var ret []Sensor
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SensorList) GetDataOk() ([]Sensor, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *SensorList) SetData(v []Sensor) {
	o.Data = v
}

// GetPagination returns the Pagination field value
func (o *SensorList) GetPagination() Pagination {
	if o == nil {
		var ret Pagination
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *SensorList) GetPaginationOk() (*Pagination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *SensorList) SetPagination(v Pagination) {
	o.Pagination = v
}

func (o SensorList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SensorList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["pagination"] = o.Pagination
	return toSerialize, nil
}

func (o *SensorList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"pagination",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSensorList := _SensorList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSensorList)

	if err != nil {
		return err
	}

	*o = SensorList(varSensorList)

	return err
}

type NullableSensorList struct {
	value *SensorList
	isSet bool
}

func (v NullableSensorList) Get() *SensorList {
	return v.value
}

func (v *NullableSensorList) Set(val *SensorList) {
	v.value = val
	v.isSet = true
}

func (v NullableSensorList) IsSet() bool {
	return v.isSet
}

func (v *NullableSensorList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSensorList(val *SensorList) *NullableSensorList {
	return &NullableSensorList{value: val, isSet: true}
}

func (v NullableSensorList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSensorList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
