/*
Green Space Management API

This is the API for the Green Ecolution Management System.

API version: develop
Contact: info@green-ecolution.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PluginRegisterRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PluginRegisterRequest{}

// PluginRegisterRequest struct for PluginRegisterRequest
type PluginRegisterRequest struct {
	Auth PluginAuth `json:"auth"`
	Description string `json:"description"`
	Name string `json:"name"`
	Path string `json:"path"`
	Slug string `json:"slug"`
	Version string `json:"version"`
}

type _PluginRegisterRequest PluginRegisterRequest

// NewPluginRegisterRequest instantiates a new PluginRegisterRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPluginRegisterRequest(auth PluginAuth, description string, name string, path string, slug string, version string) *PluginRegisterRequest {
	this := PluginRegisterRequest{}
	this.Auth = auth
	this.Description = description
	this.Name = name
	this.Path = path
	this.Slug = slug
	this.Version = version
	return &this
}

// NewPluginRegisterRequestWithDefaults instantiates a new PluginRegisterRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPluginRegisterRequestWithDefaults() *PluginRegisterRequest {
	this := PluginRegisterRequest{}
	return &this
}

// GetAuth returns the Auth field value
func (o *PluginRegisterRequest) GetAuth() PluginAuth {
	if o == nil {
		var ret PluginAuth
		return ret
	}

	return o.Auth
}

// GetAuthOk returns a tuple with the Auth field value
// and a boolean to check if the value has been set.
func (o *PluginRegisterRequest) GetAuthOk() (*PluginAuth, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Auth, true
}

// SetAuth sets field value
func (o *PluginRegisterRequest) SetAuth(v PluginAuth) {
	o.Auth = v
}

// GetDescription returns the Description field value
func (o *PluginRegisterRequest) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *PluginRegisterRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *PluginRegisterRequest) SetDescription(v string) {
	o.Description = v
}

// GetName returns the Name field value
func (o *PluginRegisterRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PluginRegisterRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PluginRegisterRequest) SetName(v string) {
	o.Name = v
}

// GetPath returns the Path field value
func (o *PluginRegisterRequest) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *PluginRegisterRequest) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *PluginRegisterRequest) SetPath(v string) {
	o.Path = v
}

// GetSlug returns the Slug field value
func (o *PluginRegisterRequest) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *PluginRegisterRequest) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *PluginRegisterRequest) SetSlug(v string) {
	o.Slug = v
}

// GetVersion returns the Version field value
func (o *PluginRegisterRequest) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *PluginRegisterRequest) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *PluginRegisterRequest) SetVersion(v string) {
	o.Version = v
}

func (o PluginRegisterRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PluginRegisterRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["auth"] = o.Auth
	toSerialize["description"] = o.Description
	toSerialize["name"] = o.Name
	toSerialize["path"] = o.Path
	toSerialize["slug"] = o.Slug
	toSerialize["version"] = o.Version
	return toSerialize, nil
}

func (o *PluginRegisterRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"auth",
		"description",
		"name",
		"path",
		"slug",
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPluginRegisterRequest := _PluginRegisterRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPluginRegisterRequest)

	if err != nil {
		return err
	}

	*o = PluginRegisterRequest(varPluginRegisterRequest)

	return err
}

type NullablePluginRegisterRequest struct {
	value *PluginRegisterRequest
	isSet bool
}

func (v NullablePluginRegisterRequest) Get() *PluginRegisterRequest {
	return v.value
}

func (v *NullablePluginRegisterRequest) Set(val *PluginRegisterRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePluginRegisterRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePluginRegisterRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePluginRegisterRequest(val *PluginRegisterRequest) *NullablePluginRegisterRequest {
	return &NullablePluginRegisterRequest{value: val, isSet: true}
}

func (v NullablePluginRegisterRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePluginRegisterRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


