/*
Green Space Management API

This is the API for the Green Ecolution Management System.

API version: develop
Contact: info@green-ecolution.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GeoJson type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GeoJson{}

// GeoJson struct for GeoJson
type GeoJson struct {
	Bbox     []float32        `json:"bbox"`
	Features []GeoJsonFeature `json:"features"`
	Metadata GeoJSONMetadata  `json:"metadata"`
	Type     GeoJsonType      `json:"type"`
}

type _GeoJson GeoJson

// NewGeoJson instantiates a new GeoJson object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGeoJson(bbox []float32, features []GeoJsonFeature, metadata GeoJSONMetadata, type_ GeoJsonType) *GeoJson {
	this := GeoJson{}
	this.Bbox = bbox
	this.Features = features
	this.Metadata = metadata
	this.Type = type_
	return &this
}

// NewGeoJsonWithDefaults instantiates a new GeoJson object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGeoJsonWithDefaults() *GeoJson {
	this := GeoJson{}
	return &this
}

// GetBbox returns the Bbox field value
func (o *GeoJson) GetBbox() []float32 {
	if o == nil {
		var ret []float32
		return ret
	}

	return o.Bbox
}

// GetBboxOk returns a tuple with the Bbox field value
// and a boolean to check if the value has been set.
func (o *GeoJson) GetBboxOk() ([]float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Bbox, true
}

// SetBbox sets field value
func (o *GeoJson) SetBbox(v []float32) {
	o.Bbox = v
}

// GetFeatures returns the Features field value
func (o *GeoJson) GetFeatures() []GeoJsonFeature {
	if o == nil {
		var ret []GeoJsonFeature
		return ret
	}

	return o.Features
}

// GetFeaturesOk returns a tuple with the Features field value
// and a boolean to check if the value has been set.
func (o *GeoJson) GetFeaturesOk() ([]GeoJsonFeature, bool) {
	if o == nil {
		return nil, false
	}
	return o.Features, true
}

// SetFeatures sets field value
func (o *GeoJson) SetFeatures(v []GeoJsonFeature) {
	o.Features = v
}

// GetMetadata returns the Metadata field value
func (o *GeoJson) GetMetadata() GeoJSONMetadata {
	if o == nil {
		var ret GeoJSONMetadata
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *GeoJson) GetMetadataOk() (*GeoJSONMetadata, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metadata, true
}

// SetMetadata sets field value
func (o *GeoJson) SetMetadata(v GeoJSONMetadata) {
	o.Metadata = v
}

// GetType returns the Type field value
func (o *GeoJson) GetType() GeoJsonType {
	if o == nil {
		var ret GeoJsonType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GeoJson) GetTypeOk() (*GeoJsonType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GeoJson) SetType(v GeoJsonType) {
	o.Type = v
}

func (o GeoJson) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GeoJson) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["bbox"] = o.Bbox
	toSerialize["features"] = o.Features
	toSerialize["metadata"] = o.Metadata
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *GeoJson) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bbox",
		"features",
		"metadata",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGeoJson := _GeoJson{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGeoJson)

	if err != nil {
		return err
	}

	*o = GeoJson(varGeoJson)

	return err
}

type NullableGeoJson struct {
	value *GeoJson
	isSet bool
}

func (v NullableGeoJson) Get() *GeoJson {
	return v.value
}

func (v *NullableGeoJson) Set(val *GeoJson) {
	v.value = val
	v.isSet = true
}

func (v NullableGeoJson) IsSet() bool {
	return v.isSet
}

func (v *NullableGeoJson) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGeoJson(val *GeoJson) *NullableGeoJson {
	return &NullableGeoJson{value: val, isSet: true}
}

func (v NullableGeoJson) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGeoJson) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
