/*
Green Space Management API

This is the API for the Green Ecolution Management System.

API version: develop
Contact: info@green-ecolution.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PluginAuth type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PluginAuth{}

// PluginAuth struct for PluginAuth
type PluginAuth struct {
	ClientId     string `json:"client_id"`
	ClientSecret string `json:"client_secret"`
}

type _PluginAuth PluginAuth

// NewPluginAuth instantiates a new PluginAuth object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPluginAuth(clientId string, clientSecret string) *PluginAuth {
	this := PluginAuth{}
	this.ClientId = clientId
	this.ClientSecret = clientSecret
	return &this
}

// NewPluginAuthWithDefaults instantiates a new PluginAuth object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPluginAuthWithDefaults() *PluginAuth {
	this := PluginAuth{}
	return &this
}

// GetClientId returns the ClientId field value
func (o *PluginAuth) GetClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value
// and a boolean to check if the value has been set.
func (o *PluginAuth) GetClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientId, true
}

// SetClientId sets field value
func (o *PluginAuth) SetClientId(v string) {
	o.ClientId = v
}

// GetClientSecret returns the ClientSecret field value
func (o *PluginAuth) GetClientSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value
// and a boolean to check if the value has been set.
func (o *PluginAuth) GetClientSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientSecret, true
}

// SetClientSecret sets field value
func (o *PluginAuth) SetClientSecret(v string) {
	o.ClientSecret = v
}

func (o PluginAuth) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PluginAuth) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["client_id"] = o.ClientId
	toSerialize["client_secret"] = o.ClientSecret
	return toSerialize, nil
}

func (o *PluginAuth) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"client_id",
		"client_secret",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPluginAuth := _PluginAuth{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPluginAuth)

	if err != nil {
		return err
	}

	*o = PluginAuth(varPluginAuth)

	return err
}

type NullablePluginAuth struct {
	value *PluginAuth
	isSet bool
}

func (v NullablePluginAuth) Get() *PluginAuth {
	return v.value
}

func (v *NullablePluginAuth) Set(val *PluginAuth) {
	v.value = val
	v.isSet = true
}

func (v NullablePluginAuth) IsSet() bool {
	return v.isSet
}

func (v *NullablePluginAuth) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePluginAuth(val *PluginAuth) *NullablePluginAuth {
	return &NullablePluginAuth{value: val, isSet: true}
}

func (v NullablePluginAuth) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePluginAuth) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
