/*
Green Space Management API

This is the API for the Green Ecolution Management System.

API version: develop
Contact: info@green-ecolution.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TreeUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TreeUpdate{}

// TreeUpdate struct for TreeUpdate
type TreeUpdate struct {
	Description string `json:"description"`
	Latitude float32 `json:"latitude"`
	Longitude float32 `json:"longitude"`
	PlantingYear int32 `json:"planting_year"`
	Readonly bool `json:"readonly"`
	SensorId *string `json:"sensor_id,omitempty"`
	Species string `json:"species"`
	TreeClusterId *int32 `json:"tree_cluster_id,omitempty"`
	TreeNumber string `json:"tree_number"`
}

type _TreeUpdate TreeUpdate

// NewTreeUpdate instantiates a new TreeUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTreeUpdate(description string, latitude float32, longitude float32, plantingYear int32, readonly bool, species string, treeNumber string) *TreeUpdate {
	this := TreeUpdate{}
	this.Description = description
	this.Latitude = latitude
	this.Longitude = longitude
	this.PlantingYear = plantingYear
	this.Readonly = readonly
	this.Species = species
	this.TreeNumber = treeNumber
	return &this
}

// NewTreeUpdateWithDefaults instantiates a new TreeUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTreeUpdateWithDefaults() *TreeUpdate {
	this := TreeUpdate{}
	return &this
}

// GetDescription returns the Description field value
func (o *TreeUpdate) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *TreeUpdate) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *TreeUpdate) SetDescription(v string) {
	o.Description = v
}

// GetLatitude returns the Latitude field value
func (o *TreeUpdate) GetLatitude() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Latitude
}

// GetLatitudeOk returns a tuple with the Latitude field value
// and a boolean to check if the value has been set.
func (o *TreeUpdate) GetLatitudeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Latitude, true
}

// SetLatitude sets field value
func (o *TreeUpdate) SetLatitude(v float32) {
	o.Latitude = v
}

// GetLongitude returns the Longitude field value
func (o *TreeUpdate) GetLongitude() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Longitude
}

// GetLongitudeOk returns a tuple with the Longitude field value
// and a boolean to check if the value has been set.
func (o *TreeUpdate) GetLongitudeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Longitude, true
}

// SetLongitude sets field value
func (o *TreeUpdate) SetLongitude(v float32) {
	o.Longitude = v
}

// GetPlantingYear returns the PlantingYear field value
func (o *TreeUpdate) GetPlantingYear() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PlantingYear
}

// GetPlantingYearOk returns a tuple with the PlantingYear field value
// and a boolean to check if the value has been set.
func (o *TreeUpdate) GetPlantingYearOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlantingYear, true
}

// SetPlantingYear sets field value
func (o *TreeUpdate) SetPlantingYear(v int32) {
	o.PlantingYear = v
}

// GetReadonly returns the Readonly field value
func (o *TreeUpdate) GetReadonly() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Readonly
}

// GetReadonlyOk returns a tuple with the Readonly field value
// and a boolean to check if the value has been set.
func (o *TreeUpdate) GetReadonlyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Readonly, true
}

// SetReadonly sets field value
func (o *TreeUpdate) SetReadonly(v bool) {
	o.Readonly = v
}

// GetSensorId returns the SensorId field value if set, zero value otherwise.
func (o *TreeUpdate) GetSensorId() string {
	if o == nil || IsNil(o.SensorId) {
		var ret string
		return ret
	}
	return *o.SensorId
}

// GetSensorIdOk returns a tuple with the SensorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TreeUpdate) GetSensorIdOk() (*string, bool) {
	if o == nil || IsNil(o.SensorId) {
		return nil, false
	}
	return o.SensorId, true
}

// HasSensorId returns a boolean if a field has been set.
func (o *TreeUpdate) HasSensorId() bool {
	if o != nil && !IsNil(o.SensorId) {
		return true
	}

	return false
}

// SetSensorId gets a reference to the given string and assigns it to the SensorId field.
func (o *TreeUpdate) SetSensorId(v string) {
	o.SensorId = &v
}

// GetSpecies returns the Species field value
func (o *TreeUpdate) GetSpecies() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Species
}

// GetSpeciesOk returns a tuple with the Species field value
// and a boolean to check if the value has been set.
func (o *TreeUpdate) GetSpeciesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Species, true
}

// SetSpecies sets field value
func (o *TreeUpdate) SetSpecies(v string) {
	o.Species = v
}

// GetTreeClusterId returns the TreeClusterId field value if set, zero value otherwise.
func (o *TreeUpdate) GetTreeClusterId() int32 {
	if o == nil || IsNil(o.TreeClusterId) {
		var ret int32
		return ret
	}
	return *o.TreeClusterId
}

// GetTreeClusterIdOk returns a tuple with the TreeClusterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TreeUpdate) GetTreeClusterIdOk() (*int32, bool) {
	if o == nil || IsNil(o.TreeClusterId) {
		return nil, false
	}
	return o.TreeClusterId, true
}

// HasTreeClusterId returns a boolean if a field has been set.
func (o *TreeUpdate) HasTreeClusterId() bool {
	if o != nil && !IsNil(o.TreeClusterId) {
		return true
	}

	return false
}

// SetTreeClusterId gets a reference to the given int32 and assigns it to the TreeClusterId field.
func (o *TreeUpdate) SetTreeClusterId(v int32) {
	o.TreeClusterId = &v
}

// GetTreeNumber returns the TreeNumber field value
func (o *TreeUpdate) GetTreeNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TreeNumber
}

// GetTreeNumberOk returns a tuple with the TreeNumber field value
// and a boolean to check if the value has been set.
func (o *TreeUpdate) GetTreeNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TreeNumber, true
}

// SetTreeNumber sets field value
func (o *TreeUpdate) SetTreeNumber(v string) {
	o.TreeNumber = v
}

func (o TreeUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TreeUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["description"] = o.Description
	toSerialize["latitude"] = o.Latitude
	toSerialize["longitude"] = o.Longitude
	toSerialize["planting_year"] = o.PlantingYear
	toSerialize["readonly"] = o.Readonly
	if !IsNil(o.SensorId) {
		toSerialize["sensor_id"] = o.SensorId
	}
	toSerialize["species"] = o.Species
	if !IsNil(o.TreeClusterId) {
		toSerialize["tree_cluster_id"] = o.TreeClusterId
	}
	toSerialize["tree_number"] = o.TreeNumber
	return toSerialize, nil
}

func (o *TreeUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"description",
		"latitude",
		"longitude",
		"planting_year",
		"readonly",
		"species",
		"tree_number",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTreeUpdate := _TreeUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTreeUpdate)

	if err != nil {
		return err
	}

	*o = TreeUpdate(varTreeUpdate)

	return err
}

type NullableTreeUpdate struct {
	value *TreeUpdate
	isSet bool
}

func (v NullableTreeUpdate) Get() *TreeUpdate {
	return v.value
}

func (v *NullableTreeUpdate) Set(val *TreeUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableTreeUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableTreeUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTreeUpdate(val *TreeUpdate) *NullableTreeUpdate {
	return &NullableTreeUpdate{value: val, isSet: true}
}

func (v NullableTreeUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTreeUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


