/*
Openrouteservice

This is the openrouteservice API documentation for ORS Core-Version 9.0.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).

API version: v2
Contact: support@smartmobility.heigit.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ors

import (
	"encoding/json"
)

// checks if the GeoJSONIsochronesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GeoJSONIsochronesResponse{}

// GeoJSONIsochronesResponse struct for GeoJSONIsochronesResponse
type GeoJSONIsochronesResponse struct {
	Type *string `json:"type,omitempty"`
	// Bounding box that covers all returned isochrones
	Bbox []float64 `json:"bbox,omitempty"`
	Features []GeoJSONIsochroneBase `json:"features,omitempty"`
	Metadata *IsochronesResponseInfo `json:"metadata,omitempty"`
}

// NewGeoJSONIsochronesResponse instantiates a new GeoJSONIsochronesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGeoJSONIsochronesResponse() *GeoJSONIsochronesResponse {
	this := GeoJSONIsochronesResponse{}
	return &this
}

// NewGeoJSONIsochronesResponseWithDefaults instantiates a new GeoJSONIsochronesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGeoJSONIsochronesResponseWithDefaults() *GeoJSONIsochronesResponse {
	this := GeoJSONIsochronesResponse{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GeoJSONIsochronesResponse) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoJSONIsochronesResponse) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GeoJSONIsochronesResponse) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *GeoJSONIsochronesResponse) SetType(v string) {
	o.Type = &v
}

// GetBbox returns the Bbox field value if set, zero value otherwise.
func (o *GeoJSONIsochronesResponse) GetBbox() []float64 {
	if o == nil || IsNil(o.Bbox) {
		var ret []float64
		return ret
	}
	return o.Bbox
}

// GetBboxOk returns a tuple with the Bbox field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoJSONIsochronesResponse) GetBboxOk() ([]float64, bool) {
	if o == nil || IsNil(o.Bbox) {
		return nil, false
	}
	return o.Bbox, true
}

// HasBbox returns a boolean if a field has been set.
func (o *GeoJSONIsochronesResponse) HasBbox() bool {
	if o != nil && !IsNil(o.Bbox) {
		return true
	}

	return false
}

// SetBbox gets a reference to the given []float64 and assigns it to the Bbox field.
func (o *GeoJSONIsochronesResponse) SetBbox(v []float64) {
	o.Bbox = v
}

// GetFeatures returns the Features field value if set, zero value otherwise.
func (o *GeoJSONIsochronesResponse) GetFeatures() []GeoJSONIsochroneBase {
	if o == nil || IsNil(o.Features) {
		var ret []GeoJSONIsochroneBase
		return ret
	}
	return o.Features
}

// GetFeaturesOk returns a tuple with the Features field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoJSONIsochronesResponse) GetFeaturesOk() ([]GeoJSONIsochroneBase, bool) {
	if o == nil || IsNil(o.Features) {
		return nil, false
	}
	return o.Features, true
}

// HasFeatures returns a boolean if a field has been set.
func (o *GeoJSONIsochronesResponse) HasFeatures() bool {
	if o != nil && !IsNil(o.Features) {
		return true
	}

	return false
}

// SetFeatures gets a reference to the given []GeoJSONIsochroneBase and assigns it to the Features field.
func (o *GeoJSONIsochronesResponse) SetFeatures(v []GeoJSONIsochroneBase) {
	o.Features = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *GeoJSONIsochronesResponse) GetMetadata() IsochronesResponseInfo {
	if o == nil || IsNil(o.Metadata) {
		var ret IsochronesResponseInfo
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoJSONIsochronesResponse) GetMetadataOk() (*IsochronesResponseInfo, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *GeoJSONIsochronesResponse) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given IsochronesResponseInfo and assigns it to the Metadata field.
func (o *GeoJSONIsochronesResponse) SetMetadata(v IsochronesResponseInfo) {
	o.Metadata = &v
}

func (o GeoJSONIsochronesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GeoJSONIsochronesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Bbox) {
		toSerialize["bbox"] = o.Bbox
	}
	if !IsNil(o.Features) {
		toSerialize["features"] = o.Features
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

type NullableGeoJSONIsochronesResponse struct {
	value *GeoJSONIsochronesResponse
	isSet bool
}

func (v NullableGeoJSONIsochronesResponse) Get() *GeoJSONIsochronesResponse {
	return v.value
}

func (v *NullableGeoJSONIsochronesResponse) Set(val *GeoJSONIsochronesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGeoJSONIsochronesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGeoJSONIsochronesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGeoJSONIsochronesResponse(val *GeoJSONIsochronesResponse) *NullableGeoJSONIsochronesResponse {
	return &NullableGeoJSONIsochronesResponse{value: val, isSet: true}
}

func (v NullableGeoJSONIsochronesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGeoJSONIsochronesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


