/*
Openrouteservice

This is the openrouteservice API documentation for ORS Core-Version 9.0.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).

API version: v2
Contact: support@smartmobility.heigit.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ors

import (
	"encoding/json"
)

// checks if the GeoJSONRouteResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GeoJSONRouteResponse{}

// GeoJSONRouteResponse struct for GeoJSONRouteResponse
type GeoJSONRouteResponse struct {
	Type *string `json:"type,omitempty"`
	// Bounding box that covers all returned routes
	Bbox []float64 `json:"bbox,omitempty"`
	Features []map[string]interface{} `json:"features,omitempty"`
	Metadata *RouteResponseInfo `json:"metadata,omitempty"`
}

// NewGeoJSONRouteResponse instantiates a new GeoJSONRouteResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGeoJSONRouteResponse() *GeoJSONRouteResponse {
	this := GeoJSONRouteResponse{}
	return &this
}

// NewGeoJSONRouteResponseWithDefaults instantiates a new GeoJSONRouteResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGeoJSONRouteResponseWithDefaults() *GeoJSONRouteResponse {
	this := GeoJSONRouteResponse{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GeoJSONRouteResponse) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoJSONRouteResponse) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GeoJSONRouteResponse) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *GeoJSONRouteResponse) SetType(v string) {
	o.Type = &v
}

// GetBbox returns the Bbox field value if set, zero value otherwise.
func (o *GeoJSONRouteResponse) GetBbox() []float64 {
	if o == nil || IsNil(o.Bbox) {
		var ret []float64
		return ret
	}
	return o.Bbox
}

// GetBboxOk returns a tuple with the Bbox field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoJSONRouteResponse) GetBboxOk() ([]float64, bool) {
	if o == nil || IsNil(o.Bbox) {
		return nil, false
	}
	return o.Bbox, true
}

// HasBbox returns a boolean if a field has been set.
func (o *GeoJSONRouteResponse) HasBbox() bool {
	if o != nil && !IsNil(o.Bbox) {
		return true
	}

	return false
}

// SetBbox gets a reference to the given []float64 and assigns it to the Bbox field.
func (o *GeoJSONRouteResponse) SetBbox(v []float64) {
	o.Bbox = v
}

// GetFeatures returns the Features field value if set, zero value otherwise.
func (o *GeoJSONRouteResponse) GetFeatures() []map[string]interface{} {
	if o == nil || IsNil(o.Features) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Features
}

// GetFeaturesOk returns a tuple with the Features field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoJSONRouteResponse) GetFeaturesOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Features) {
		return nil, false
	}
	return o.Features, true
}

// HasFeatures returns a boolean if a field has been set.
func (o *GeoJSONRouteResponse) HasFeatures() bool {
	if o != nil && !IsNil(o.Features) {
		return true
	}

	return false
}

// SetFeatures gets a reference to the given []map[string]interface{} and assigns it to the Features field.
func (o *GeoJSONRouteResponse) SetFeatures(v []map[string]interface{}) {
	o.Features = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *GeoJSONRouteResponse) GetMetadata() RouteResponseInfo {
	if o == nil || IsNil(o.Metadata) {
		var ret RouteResponseInfo
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoJSONRouteResponse) GetMetadataOk() (*RouteResponseInfo, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *GeoJSONRouteResponse) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given RouteResponseInfo and assigns it to the Metadata field.
func (o *GeoJSONRouteResponse) SetMetadata(v RouteResponseInfo) {
	o.Metadata = &v
}

func (o GeoJSONRouteResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GeoJSONRouteResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Bbox) {
		toSerialize["bbox"] = o.Bbox
	}
	if !IsNil(o.Features) {
		toSerialize["features"] = o.Features
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

type NullableGeoJSONRouteResponse struct {
	value *GeoJSONRouteResponse
	isSet bool
}

func (v NullableGeoJSONRouteResponse) Get() *GeoJSONRouteResponse {
	return v.value
}

func (v *NullableGeoJSONRouteResponse) Set(val *GeoJSONRouteResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGeoJSONRouteResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGeoJSONRouteResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGeoJSONRouteResponse(val *GeoJSONRouteResponse) *NullableGeoJSONRouteResponse {
	return &NullableGeoJSONRouteResponse{value: val, isSet: true}
}

func (v NullableGeoJSONRouteResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGeoJSONRouteResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


