name: Build and Push Docker Image Production

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  merge_and_publish_prod:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true &&
      (startsWith(github.event.pull_request.head.ref, 'release/') || startsWith(github.event.pull_request.head.ref, 'hotfix/'))
    permissions:
      contents: write
      packages: write
      actions: write
      pull-requests: write
    outputs:
      RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
    steps:
      - name: Extract version from branch name (for release branches)
        if: startsWith(github.event.pull_request.head.ref, 'release/')
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          VERSION=${BRANCH_NAME#release/}

          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Extract version from branch name (for hotfix branches)
        if: startsWith(github.event.pull_request.head.ref, 'hotfix/')
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          VERSION=${BRANCH_NAME#hotfix/}

          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create Release
        uses: thomaseizinger/create-release@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GREEN_ECOLUTION_PAT }} 
        with:
          target_commitish: ${{ github.event.pull_request.merge_commit_sha }}
          tag_name: ${{ env.RELEASE_VERSION }}
          name: ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false

      - name: Merge main into develop branch
        uses: thomaseizinger/create-pull-request@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: main
          base: develop
          title: Merge main into develop branch
          body: |
            This PR merges the main branch back into develop.
            This happens to ensure that the updates that happend on the release branch, i.e. CHANGELOG and manifest updates are also present on the develop branch.

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set lower case owner name
        run: |
          echo "REPO_LC=${REPO,,}" >>${GITHUB_ENV}
        env:
          REPO: "${{ github.repository }}"

      - name: get build time
        run: |
          echo "BUILD_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >>${GITHUB_ENV}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            APP_VERSION=${{env.RELEASE_VERSION}}
            APP_GIT_COMMIT=${{env.COMMIT_SHA}}
            APP_GIT_BRANCH=main
            APP_BUILD_TIME=${{env.BUILD_TIME}}
            APP_GIT_REPOSITORY=${{github.repository}}
          file: ./.docker/Dockerfile.prod
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ env.REPO_LC }}:${{ env.RELEASE_VERSION }}, ghcr.io/${{ env.REPO_LC }}:latest

      - name: Notify management repo to update submodules
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GREEN_ECOLUTION_PAT }}
          repository: green-ecolution/green-ecolution-management
          event-type: "update-submodules-production"
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ env.COMMIT_SHA }}", "version": "${{ env.RELEASE_VERSION }}", "from": "backend"}'

  upload_api_docs_prod:
    name: Upload API Docs Production
    needs: merge_and_publish_prod
    env:
      RELEASE_VERSION: ${{ needs.merge_and_publish_prod.outputs.RELEASE_VERSION }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Go generate
        run: make generate

      - name: Move swagger docs
        run: mv ./docs/swagger.json ./docs/api-docs-${{ env.RELEASE_VERSION }}.json

      - name: Upload API Docs
        uses: actions/upload-artifact@v4
        with:
          name: api-docs-${{ env.RELEASE_VERSION }}.json
          path: ./docs/api-docs-${{ env.RELEASE_VERSION }}.json
